<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Adblock Filter List</string>
    <key>scopeName</key>
    <string>text.adblock</string>
    <key>uuid</key>
    <string>255911D9-0A43-46FA-A213-62EE6E14CF16</string>
    <key>fileTypes</key>
    <array>
      <string>adblock</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#adblockAgent</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#preprocessor</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#snippetRulesABP</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#cssRules</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#scriptletRules</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#scriptletRulesUBO</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#jsRules</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#contentRules</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#elemhideRules</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#basicRulesNoUrl</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#basicRulesRegex</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#basicRules</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>adblockAgent</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>^(\[)([^\]]+)(\])\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.array.start.adblock.agent</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#adblockData</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>;</string>
                    <key>name</key>
                    <string>punctuation.separator</string>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>invalid.illegal</string>
                    <key>match</key>
                    <string>.*</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.array.end.adblock.agent</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>adblockData</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?:\s*)([Aa]d[Bb]lock(?:\s[Pp]lus)?|u[Bb]lock(?:\s[Oo]rigin)?|[Aa]d[Gg]uard)(?:\s+(\d+(?:\.\d+)*+\+?))?(?:\s*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.language.agent.adblocker.name</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.decimal</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>preprocessor</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>^(!#if)(\s)(.*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.preprocessor.directive</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.delimiter.whitespace</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>name</key>
                    <string>constant.language.platform.name</string>
                    <key>match</key>
                    <string>[A-Za-z]+[\w_-]*</string>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.logical.and</string>
                    <key>match</key>
                    <string>&amp;&amp;</string>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.logical.or</string>
                    <key>match</key>
                    <string>\|\|</string>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.logical.not</string>
                    <key>match</key>
                    <string>!</string>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.characters.parenthesis.open</string>
                    <key>match</key>
                    <string>\(</string>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.characters.parenthesis.close</string>
                    <key>match</key>
                    <string>\)</string>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.delimiter.whitespace</string>
                    <key>match</key>
                    <string>\s+</string>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>invalid.illegal</string>
                    <key>match</key>
                    <string>.*</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>^(!#include) (.*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.preprocessor.directive</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.unquoted</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>^(!#else)(\s*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.preprocessor.directive</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.delimiter.whitespace</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>^(!#endif)(\s*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.preprocessor.directive</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.delimiter.whitespace</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>^(!#safari_cb_affinity)(.*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.preprocessor.directive</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>name</key>
                    <string>constant.language.contentblocker.name</string>
                    <key>match</key>
                    <string>(all|general|privacy|social|security|other|custom|advanced)</string>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.characters</string>
                    <key>match</key>
                    <string>(\(|\)|,)</string>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>invalid.illegal</string>
                    <key>match</key>
                    <string>.*</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>^(!\+) (.*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.preprocessor.hint</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.hint.name</string>
                    <key>match</key>
                    <string>(NOT_OPTIMIZED|OPTIMIZED|PLATFORM|NOT_PLATFORM|NOT_VALIDATE)</string>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>constant.language.platform.name</string>
                    <key>match</key>
                    <string>(windows|mac|cli|android|ios|ext_chromium_mv3|ext_chromium|ext_ff|ext_edge|ext_opera|ext_ublock|ext_safari|ext_android_cb)</string>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.characters</string>
                    <key>match</key>
                    <string>(\(|\)|,)</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>^!#(?!#).+$</string>
            <key>name</key>
            <string>invalid.illegal.preprocessor</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.line.exclamation-sign</string>
            <key>match</key>
            <string>^!.*</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.hashtag-sign</string>
            <key>match</key>
            <string>^#(?!(?:@?(?:\$?\?|\$|%)?#)).*</string>
          </dict>
        </array>
      </dict>
      <key>elemhideRules</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>^(\[.+?\])?(.*?)(#@?\??#\^?)(.+)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#cosmeticRulesOptions</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#domainListCommaSeparated</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.control.adblock</string>
              </dict>
              <key>4</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#cssSelector</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>snippetRulesABP</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>^(.*?)(#@?\$#)([^{]+)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#domainListCommaSeparated</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>constant.character.snippet.adblock</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>cssRules</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>^(\[.+?\])?(.*?)(#@?\$\??#)(.+)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#cosmeticRulesOptions</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#domainListCommaSeparated</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.control.adblock</string>
              </dict>
              <key>4</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#cssStyle</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>contentRules</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>^(\[.+?\])?(.*?)(\$@?\$)(.+?)(\[.+)?$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#cosmeticRulesOptions</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#domainListCommaSeparated</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.control.adblock</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.adblock</string>
              </dict>
              <key>5</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#contentAttributes</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>scriptletRules</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#exceptionScriptletRules</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#blockingScriptletRules</string>
          </dict>
        </array>
      </dict>
      <key>exceptionScriptletRules</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>^\s*(\[.+?\])?(.*)?(\#@%\#)(\/\/scriptlet)(\()(.*)?(\))\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#cosmeticRulesOptions</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#domainListCommaSeparated</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.control.adblock</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.adblock</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.adblock</string>
              </dict>
              <key>6</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#emptyScriptletFunction</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#scriptletFunction</string>
                  </dict>
                </array>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.adblock</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>blockingScriptletRules</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>^\s*(\[.+?\])?(.*)?(\#%\#)(\/\/scriptlet)(\()(.*\S.*)(\))\s*</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#cosmeticRulesOptions</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#domainListCommaSeparated</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.control.adblock</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.adblock</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.adblock</string>
              </dict>
              <key>6</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#scriptletFunction</string>
                  </dict>
                </array>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.adblock</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>scriptletRulesUBO</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>^(.*?)(#@?#)(\+js)(\()(.+)(\)\s*)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#domainListCommaSeparated</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.adblock</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.adblock</string>
              </dict>
              <key>5</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#scriptletFunctionUBO</string>
                  </dict>
                </array>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.adblock</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>jsRules</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^(.*?)(#@?%#(?!\/\/scriptlet))</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#domainListCommaSeparated</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.adblock</string>
              </dict>
            </dict>
            <key>end</key>
            <string>$</string>
            <key>contentName</key>
            <string>source.js</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.js</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>^(.*?)(#@?%#)(.+)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#domainListCommaSeparated</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>basicRulesNoUrl</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>^(\$)(.+)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#basicRulesOptions</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>basicRulesRegex</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>^(\/[^\/\\]*(?:\\.[^\/\\]*)*\/[dgimsuy]*)(?:(\$)(.+))?$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#regularExpression</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#basicRulesOptions</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>basicRules</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>^(.+?)((\$(?!\/))(.*))?$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#urlPattern</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.control.adblock</string>
              </dict>
              <key>4</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#basicRulesOptions</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>regularExpression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(/)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.regex.begin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>((?&lt;!\\)/)([dgimsuy]*)?</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.regex.end</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.regex</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>string.regexp</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(?&lt;!\\)([/\^\$\|])</string>
                <key>name</key>
                <string>keyword.control.regex</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>urlPattern</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.regexp.adblock</string>
            <key>match</key>
            <string>^(@@)?(\/)(.+)\/$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>^@@\|?\|?</string>
            <key>name</key>
            <string>keyword.other.adblock</string>
          </dict>
          <dict>
            <key>match</key>
            <string>^\|\|</string>
            <key>name</key>
            <string>keyword.other.adblock</string>
          </dict>
          <dict>
            <key>match</key>
            <string>^\|</string>
            <key>name</key>
            <string>keyword.other.adblock</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\|$</string>
            <key>name</key>
            <string>keyword.other.adblock</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\^</string>
            <key>name</key>
            <string>keyword.other.adblock</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\*</string>
            <key>name</key>
            <string>keyword.other.adblock</string>
          </dict>
        </array>
      </dict>
      <key>basicRulesOptions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>replace=((\/)(((\\\/)|[^,/]|(\\,))+?)(\/)(((\\\/)|[^,/]|(\\,))*?)(\/)([a-z]*))</string>
            <key>name</key>
            <string>keyword.other.adblock</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.regexp.adblock</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(domain|denyallow|from|to)(=)([^,]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#domainListPipeSeparated</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(app)(=)([^,]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#appListPipeSeparated</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(dnstype)(=)([^,]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#dnsTypesPipeSeparated</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(client|ctag)(=)(((\\,)|[^,])+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#dnsClientsPipeSeparated</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(redirect|redirect-rule|csp|cookie)(=)?(((\\,)|[^,])+)?</string>
            <key>name</key>
            <string>keyword.other.adblock</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.unquoted.adblock</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(dnsrewrite)(=)(((\\,)|[^,])+)</string>
            <key>name</key>
            <string>keyword.other.adblock</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.delimiter</string>
                    <key>match</key>
                    <string>;</string>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>string.unquoted.adblock</string>
                    <key>match</key>
                    <string>[^;]*</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(removeheader)(=)?(((\\,)|[^,])+)?</string>
            <key>name</key>
            <string>keyword.other.adblock</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.delimiter</string>
                    <key>match</key>
                    <string>:</string>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>string.unquoted.adblock</string>
                    <key>match</key>
                    <string>[^:]*</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(rewrite)(=)(abp-resource:)([^,]+)</string>
            <key>name</key>
            <string>keyword.other.adblock</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.unquoted.adblock</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(removeparam|queryprune)(=)?(~)?(((\\,)|[^,])+)?</string>
            <key>name</key>
            <string>keyword.other.adblock</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.unquoted.adblock</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(method)(=)([^,]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>(?i)(connect|delete|get|head|options|patch|post|put)</string>
                    <key>name</key>
                    <string>string.unquoted.adblock</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>~|\|</string>
                    <key>name</key>
                    <string>keyword.operator.adblock</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>.+</string>
                    <key>name</key>
                    <string>invalid.illegal.method-value</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(referrerpolicy)(=)?((\w|-)+)?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>(?i)(no-referrer|no-referrer-when-downgrade|origin|origin-when-cross-origin|same-origin|strict-origin|strict-origin-when-cross-origin|unsafe-url)</string>
                    <key>name</key>
                    <string>string.unquoted.adblock</string>
                  </dict>
                  <dict>
                    <key>match</key>
                    <string>~|\|.+</string>
                    <key>name</key>
                    <string>invalid.illegal.referrerpolicy-value</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(permissions)(=)?(((\\,)|[^,])+)?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.unquoted.adblock</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(header)(=)([^,]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.unquoted.adblock</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(inline-script|inline-font|mp4|empty|badfilter|genericblock|generichide|network|popup|popunder|important|replace|stealth)</string>
            <key>name</key>
            <string>keyword.other.adblock</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(~?)(first-party|third-party|match-case|elemhide|content|jsinject|urlblock|extension|all|strict1p|strict3p|1p|3p|css|frame|ghide|ehide|shide|specifichide)</string>
            <key>name</key>
            <string>keyword.other.adblock</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(~)?(document|doc|font|image|media|object|other|ping|beacon|script|stylesheet|css|subdocument|frame|websocket|xmlhttprequest|xhr|webrtc)(,|$)</string>
            <key>name</key>
            <string>keyword.other.adblock</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(~)?(object-subrequest)</string>
            <key>name</key>
            <string>invalid.illegal.removed.modifier</string>
          </dict>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.definition.adblock</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\$</string>
            <key>name</key>
            <string>invalid.illegal.redundant.modifier.separator</string>
          </dict>
        </array>
      </dict>
      <key>cosmeticRulesOptions</key>
      <dict>
        <key>match</key>
        <string>(\[)(.+?)(\])</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.adblock</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(path)(=)(((\\,)|[^,])+)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.adblock</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.adblock</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>string.unquoted.adblock</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>match</key>
                <string>(domain)(=)([^,]+)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.adblock</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.adblock</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#domainListPipeSeparated</string>
                      </dict>
                    </array>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>match</key>
                <string>(app)(=)([^,]+)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.adblock</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.adblock</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#appListPipeSeparated</string>
                      </dict>
                    </array>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>match</key>
                <string>(url)(=)([^,]+)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.adblock</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.adblock</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>string.unquoted.adblock</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>match</key>
                <string>\$</string>
                <key>name</key>
                <string>keyword.control.adblock</string>
              </dict>
              <dict>
                <key>match</key>
                <string>,</string>
                <key>name</key>
                <string>punctuation.definition.adblock</string>
              </dict>
              <dict>
                <key>name</key>
                <string>invalid.illegal.adblock</string>
                <key>match</key>
                <string>.*</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control.adblock</string>
          </dict>
        </dict>
      </dict>
      <key>contentAttributes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\[)([^"=]+?)(\=)(".+?")(\])</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.adblock</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.quoted.adblock</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.adblock</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.adblock</string>
            <key>match</key>
            <string>.*</string>
          </dict>
        </array>
      </dict>
      <key>emptyScriptletFunction</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\s*\z</string>
            <key>name</key>
            <string>entity.name.section.adblock.empty-scriptlet</string>
          </dict>
        </array>
      </dict>
      <key>scriptletFunction</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>((['|"])(.*?)(?&lt;!\\)(\2))(,\s*)?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.adblock</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.adblock</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.adblock</string>
            <key>match</key>
            <string>.*</string>
          </dict>
        </array>
      </dict>
      <key>scriptletFunctionUBO</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>((?:[^\\,]+|\\.?)*)(,|$)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.adblock</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.adblock</string>
            <key>match</key>
            <string>.*</string>
          </dict>
        </array>
      </dict>
      <key>cssStyle</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(@media[\s]+[^\{]*)(\{)([\s]*[^\{]*)(\{)([\s]*[^\}]*)(\})[\s]*(\})</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.adblock</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.adblock</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>string.quoted.adblock</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.adblock</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.adblock</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>([^{}]+)\s*((\{)(.+?)(\}))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.adblock</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.quoted.adblock</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.adblock</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.adblock</string>
            <key>match</key>
            <string>.*</string>
          </dict>
        </array>
      </dict>
      <key>cssSelector</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>entity.name.function.adblock</string>
            <key>match</key>
            <string>.+</string>
          </dict>
        </array>
      </dict>
      <key>domainListCommaSeparated</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(~?)([^,]+)(,?)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.unquoted.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.adblock</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.domain-list</string>
            <key>match</key>
            <string>.*</string>
          </dict>
        </array>
      </dict>
      <key>domainListPipeSeparated</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(~?)([^|]+)(\|?)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.unquoted.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.adblock</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.domain-list</string>
            <key>match</key>
            <string>.*</string>
          </dict>
        </array>
      </dict>
      <key>appListPipeSeparated</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>((~?)([a-zA-Z0-9.-_]+)(\|?))</string>
            <key>captures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.unquoted.adblock</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.adblock</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.app-list</string>
            <key>match</key>
            <string>.*</string>
          </dict>
        </array>
      </dict>
      <key>dnsTypesPipeSeparated</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>((~?)([a-zA-Z0-9.-_]+)(\|?))</string>
            <key>captures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.unquoted.adblock</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.adblock</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.app-list</string>
            <key>match</key>
            <string>.*</string>
          </dict>
        </array>
      </dict>
      <key>dnsClientsPipeSeparated</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>((~?)([^|]+)(\|?))</string>
            <key>captures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.adblock</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.unquoted.adblock</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.adblock</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.app-list</string>
            <key>match</key>
            <string>.*</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>
